### PR TITLE
Cache the topology and the endpoint mappings to speed up cstar on subsequent calls

### PR DESCRIPTION
**Pull request by adejanovski**
nodetool status will get used to check the state of each node, but the topology won't be recomputed unless the list of hosts changes or the schema gets modified (replication factors could be changed).

### CODE REVIEW

**Comment by yakirgb** [comment]
This is great, we have many issues like:
```
15:45:03 Retry :  False
15:46:37 Traceback (most recent call last):
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/cstarcli.py", line 55, in execute_continue
15:46:37     output_directory=args.output_directory, retry=args.retry_failed)
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/jobreader.py", line 35, in read
15:46:37     return _parse(f.read(), file, output_directory, job, job_id, stop_after, max_days, endpoint_mapper, retry)
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/jobreader.py", line 89, in _parse
15:46:37     endpoint_mapping = endpoint_mapper(original_topology)
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/job.py", line 160, in get_endpoint_mapping
15:46:37     mappings.append(cstar.endpoint_mapping.parse(range_mapping, topology, lookup=ip_lookup))
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/endpoint_mapping.py", line 23, in parse
15:46:37     return _topology_map(_dns_map(_parse_range_mapping(range_mapping), lookup), topology)
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/endpoint_mapping.py", line 57, in _topology_map
15:46:37     host = topology.get_host(raw_host)
15:46:37   File "/usr/local/lib/python3.6/site-packages/cstar/topology.py", line 51, in get_host
15:46:37     raise UnknownHost(ip)
15:46:37 cstar.exceptions.UnknownHost: Unknown host: 10.21.34.15
```
And the option of `--resolve-hostnames` will help.
Thanks.

**Comment by adejanovski** [comment]
Hi @yakirgb,

Do you mean that this PR generates this error with the unknown host or you're already experiencing it with the current released version?
Seems like you were resuming a job, was node `10.21.34.15` still part of the ring at that time?

**Comment by yakirgb** [comment]
@adejanovski i'm already have issue with current release and hope that your PR will help to me.
Thanks.

**Comment by yakirgb** [comment]
Something interesting and maybe need to improve, the first run was:
`/usr/local/bin/cstar run --command=/home/cassandra/scripts/cassandra_restart.sh --seed-host=cass101.foo.com --dc-filter=cass1 --ignore-down-nodes --strategy=topology --max-concurrency=1 --ssh-lib=ssh2 --ssh-identity-file=/var/lib/foo/.ssh/id_rsa  --ssh-username=root -v `

I resumed the job via: `/usr/local/bin/cstar continue c5e2c3bf-3b13-4079-beea-c15055123f8c -v `

And got the following error on node in **other DC** and not in DC cass1:
`cstar.exceptions.UnknownHost: Unknown host: 10.21.34.15`
Any option that the check UnknownHost will be only on the DC in `--dc-filter` ?

**Comment by yakirgb** [comment]
@adejanovski can you make new release please with that fix?

**Comment by parham-pythian** [comment]
@adejanovski Do you think it would be safe to use the branch code that has this patch without `nodetool ring` or would it be better to wait for it to be merged to master?

**Comment by adejanovski** [comment]
@parham-pythian,

it's safe to use IMO. I'll probably get this PR merged real soon and cut out a new release.

**Comment by parham-pythian** [comment]
OK, perfect. Thank you, @adejanovski .

**Comment by adejanovski** [comment]
Replaced by #44

**Pull request closed without merging**
