### PR TITLE
Cache the topology and the endpoint mappings to speed up cstar on subsequent calls

### PR DESCRIPTION
**Pull request by adejanovski**
nodetool status will get used to check the state of each node, but the topology won't be recomputed unless the list of hosts changes or the schema gets modified (replication factors could be changed).
Make fqdn resolving optional.
Remove nodetool ring calls and remove the tokens from the Host objects

### CODE REVIEW

**Comment by adejanovski** [comment]
Replaces #41

**Comment by johnny5dba** [comment]
Hi @adejanovski I installed the latest version of CSTAR and looks like it's still running nodetool ring and not nodetool status it's hanging on the portion after it runs NODETOOL CFSTATS. It's hanging on the portion where it's generating end point mappings

  Warning: "nodetool ring" is used to output all the tokens of a node.
  To view status related info of a node use "nodetool status" instead.

 and 
Preheating DNS cache
Preheating done
Done loading cluster topology
Run on hosts lascassandra001s.server.hulu.com aorcassandra003s.server.hulu.com avacassandra001s.server.hulu.com lascassandra002s.server.hulu.com avacassandra002s.server.hulu.com iadcassandra003s.server.hulu.com aorcassandra002s.server.hulu.com lascassandra003s.server.hulu.com iadcassandra001s.server.hulu.com iadcassandra002s.server.hulu.com avacassandra003s.server.hulu.com aorcassandra001s.server.hulu.com
in topology lascassandra001s.server.hulu.com aorcassandra003s.server.hulu.com avacassandra001s.server.hulu.com lascassandra002s.server.hulu.com avacassandra002s.server.hulu.com iadcassandra003s.server.hulu.com aorcassandra002s.server.hulu.com lascassandra003s.server.hulu.com iadcassandra001s.server.hulu.com iadcassandra002s.server.hulu.com avacassandra003s.server.hulu.com aorcassandra001s.server.hulu.com
Generating endpoint mapping
Using ssh lib :  paramiko
Username :  None
Id file:  None
Command nodetool cfstats | grep Keyspace succeeded on host 10.88.137.49, output was Keyspace: user_devices_development
Keyspace: account_sharing_detection
Keyspace: sds
Keyspace: springshield_staging
Keyspace: cronic_dev_iad
Keyspace: ap_bulk1
Keyspace: capo_dev
Keyspace: ford
Keyspace: retail
Keyspace: tag_service_playground
Keyspace: user_devices_staging
Keyspace: system_auth
Keyspace: sds_version_3
Keyspace: tasseo_js
Keyspace: user_model_cache
Keyspace: system_traces
Keyspace: titan
Keyspace: paymentacc
Keyspace: duh_staging
Keyspace: flink_auxiliary
Keyspace: cronic_staging_iad
Keyspace: cronic_dev_las
Keyspace: nebula_staging
Keyspace: tut_dev
Keyspace: accountsharingdetection
Keyspace: clog_test
Keyspace: ap
Keyspace: btest
Keyspace: clog
Keyspace: cronic_staging_las
Keyspace: flintan_staging
Keyspace: system
Keyspace: bulktest
Keyspace: compass
Keyspace: management
Keyspace: tut_stage
Keyspace: quake
Keyspace: friendster_v1
Keyspace: apstaging
 and 
Fetching endpoint mapping for keyspace user_devices_development

**Comment by johnny5dba** [comment]
@adejanovski i updated my version of CSTAR and it's still choking on the part where its generating the endpoint_mappings right after it runs the NODETOOL CFSTATS KEYSPACE. Does the reference to nodetool ring below indicate i'm still running the old version of the code that uses nodetool ring instead of nodetool status?

**Comment by michaelsembwever** [comment]
To review this it would help with a command-by-command test documentation, making it easy to replay a scenario that sets up an example cluster, opens up ssh ports, and allows cstar to be used against it.

It is difficult to review and validate this without any such reproducible instructions. This would also be useful to create the integration test framework that is required before any integration tests can be actually added. 

Currently there are many hidden requirements (ssh, nodetool, etc) for cstar to work. Because of these I have not yet seen it work on any cluster outside of Spotify. With such test documentation, and any subsequent integration framework, it will also help smoke out those requirements (and even make them more flexible/pluggable for different types on cluster installations).

**Comment by arodrime** [comment]
Closed in favour of #51

**Comment by rzvoncek** [comment]
Finally closing in favour of #51

**Pull request closed without merging**
